Adding upstream version 3.0.9.

diff --git a/bin/live-update-initramfs b/bin/live-update-initramfs
--- a/bin/live-update-initramfs
+++ b/bin/live-update-initramfs
@@ -10,6 +10,16 @@
 
 set -e
 
+if [ ! -e /usr/sbin/update-initramfs.orig.initramfs-tools ]
+then
+	echo "E: /usr/sbin/update-initramfs.orig.initramfs-tools - command not found"
+	echo "E: On Debian based systems, update-initramfs from initramfs-tools"
+	echo "E: can be installed with:"
+	echo "E:   apt-get install initramfs-tools"
+
+	exit 1
+fi
+
 if grep -qs "boot=live" /proc/cmdline
 then
 	if grep -qs "\/live\/image" /proc/mounts
@@ -35,7 +45,7 @@ then
 	fi
 else
 	# non-live system
-	/usr/sbin/update-initramfs.initramfs-tools "${@}"
+	/usr/sbin/update-initramfs.orig.initramfs-tools "${@}"
 
 	exit "${?}"
 fi
@@ -43,7 +53,7 @@ fi
 case "${_READ_WRITE}" in
 	true)
 		# Updating initramfs
-		/usr/sbin/update-initramfs.initramfs-tools "${@}"
+		/usr/sbin/update-initramfs.orig.initramfs-tools "${@}"
 
 		# FIXME: needs to exclude initrd backup files
 		if [ "$(ls initrd.img-* | wc -l)" -gt 1 ]
diff --git a/bin/live-uptime b/bin/live-uptime
--- a/bin/live-uptime
+++ b/bin/live-uptime
@@ -10,7 +10,17 @@
 
 set -e
 
-_UPTIME="$(/usr/bin/uptime.procps)"
+if [ ! -e /usr/bin/uptime.orig.procps ]
+then
+	echo "E: /usr/bin/uptime.orig.procps - command not found"
+	echo "E: On Debian based systems, uptime from procps"
+	echo "E: can be installed with:"
+	echo "E:   apt-get install procps"
+
+	exit 1
+fi
+
+_UPTIME="$(/usr/bin/uptime.orig.procps)"
 
 _DATE_HOST="$(date +%s)"
 
