Adding warning messages if the necessary tools are not installed.

diff --git a/bin/live-update-initramfs b/bin/live-update-initramfs
--- a/bin/live-update-initramfs
+++ b/bin/live-update-initramfs
@@ -10,6 +10,16 @@
 
 set -e
 
+if [ ! -e /usr/sbin/update-initramfs.initramfs-tools ]
+then
+	echo "E: /usr/sbin/update-initramfs.initramfs-tools - command not found"
+	echo "E: On Debian based systems, update-initramfs from initramfs-tools"
+	echo "E: can be installed with:"
+	echo "E:   apt-get install initramfs-tools"
+
+	exit 1
+fi
+
 if grep -qs "boot=live" /proc/cmdline
 then
 	if grep -qs "\/live\/image" /proc/mounts
diff --git a/bin/live-uptime b/bin/live-uptime
--- a/bin/live-uptime
+++ b/bin/live-uptime
@@ -10,6 +10,16 @@
 
 set -e
 
+if [ ! -e /usr/bin/uptime.procps ]
+then
+	echo "E: /usr/bin/uptime.procps - command not found"
+	echo "E: On Debian based systems, uptime from procps"
+	echo "E: can be installed with:"
+	echo "E:   apt-get install procps"
+
+	exit 1
+fi
+
 _UPTIME="$(/usr/bin/uptime.procps)"
 
 _DATE_HOST="$(date +%s)"
